### ISSUE TITLE
utilsmodule.so

### ISSUE THREAD

**Issue by Zolko-123** [agb32/darc#2]
Hi Ali, 

I'm trying to install darc on my laptop (a Dell XPS 13 with Ubuntu 18.04) and run darc on the integrated webcam (for testing).

I was able to compile, but utilsmodule did some strange things: it was  compiled as utilsmodule.cpython-36m-x86_64-linux-gnu.so, and then the make install failed, complaining for missing utilsmodule.so. So I renamed that file to utilsmodule.so, and that worked.

But then, when running darccontrol, I get:

_WARNING - buffer.py cannot import utils
Traceback (most recent call last): 
  File "/opt/darc/bin/darccontrol", line 28, in <module> 
    import utils 
ImportError: /opt/darc/lib/python/utilsmodule.so: undefined symbol: Py_InitModule_

Any thoughts ? 
My camera is recongnised by the uvcvideo kernel module, and I can read it from /dev/video0: will darc be able to read it ?

cheers

Zoltan

**Comment by agb32** [comment]
Hi Zoltan,
I guess distutils must have changed the default name - the makefile uses python setup.py install --install-lib=. to create utilsmodule.so.

Are you using python2?  I don't think it works for python3 yet.

If you make the libcamv4l.so module, that should work with webcams - and there is an example config for using this.

**Comment by Zolko-123** [comment]
By default I have python3, but python2 is also installed. Actually, I had to change this in darccontrol:

`#!/usr/bin/env python2`

should be also in setup.py ?

**Comment by agb32** [comment]
This is in the src/Makefile, so perhaps changing that to python2 setup.py ...
utilsmodule.so: utils.c
	python setup.py build
	python setup.py install --install-lib=.

**Comment by Zolko-123** [comment]
yes, that fixed the compile issue, thanks (did a make clean before).

Now, make install fails at Check.py:

_Compiling '/opt/darc/lib/python/Check.py'...
***   File "/opt/darc/lib/python/Check.py", line 25
    print "Unable to load CustomCheck module - continuing"
                                                         ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Unable to load CustomCheck module - continuing")?_

even though I added _#!/usr/bin/env python2_ at the beginning of Check.py in the source (and it's in opt too)

**Comment by agb32** [comment]
lib/Makefile has a line:
python -c "import compileall; compileall.main()" $(PY)
Try changing that to python2...

**Comment by Zolko-123** [comment]
well done, make and make install now work without error. Now I have:

_WARNING - buffer.py cannot import utils
Traceback (most recent call last):
  File "./bin/darccontrol", line 28, in <module>
    import utils
ImportError: /opt/darc/lib/python/utilsmodule.so: undefined symbol: darc_futex_wait_

so there still is something with the utilsmodule

**Comment by agb32** [comment]
Good question, not sure about that.  darc_futex_wait is defined as an inline function in darcMutex.h, which is included by utils.c.  
Can you try changing it to static inline - line 281 of include/darcMutex.h.

**Comment by Zolko-123** [comment]
nope, still the same

**Comment by Zolko-123** [comment]
wait, no:

`ImportError: /opt/darc/lib/python/utilsmodule.so: undefined symbol: darc_futex_destroy`

**Comment by Zolko-123** [comment]
static inline ...

`darc_futex_timedwait`

**Comment by Zolko-123** [comment]
I static inlined them all, now:

`Redirecting control output
mlockall failed (you need to be running as root): Cannot allocate memory (note this probably makes no performance difference if you aren't swapping)
redirecting stdout to /dev/shm/rtcStdout0...`

with sudo:

_None None None None
Redirecting control output_

it's alive !!!!

**Comment by agb32** [comment]
Cool - could you do a pull request...

**Comment by Zolko-123** [comment]
I'll try. Right now I only downloaded the ZIP and made local changes, so not sure.

**Comment by Zolko-123** [comment]
made PR #3

**Comment by agb32** [comment]
Merged...

**Comment by Zolko-123** [comment]
Thanx. Now, all I have to do is configure and run it
