### ISSUE TITLE
darcmagic print

### ISSUE THREAD

**Issue by Zolko-123** [agb32/darc#4]
darc now runs, when I start it with configv4l.py, the LED indicator of the webcam says it's active. When killing darcmain in goes off again.

BUT: I cannot communicate with it through darcmagic because it's coded for python 2 all over, with 156 print statements in in the file. darktalkf has 68 print statements.

Any thoughts, apart from replacing all print "" by print("") by hand ?

**Comment by agb32** [comment]
There are likely to be other python3 incompatibilities - probably mostly subtle things... (strings/byte arrays, integer division, etc).
So, if you want a quick job, use python2, while if you want to do it properly, start a conversion to python3.  Actually, some of this might already have been done - Tim might know...

**Comment by Zolko-123** [comment]
yes of course, sorry:

`#!/usr/bin/env python2`
