### ISSUE TITLE
read image

### ISSUE THREAD

**Issue by Zolko-123** [agb32/darc#5]
OK, so I have now a running system I think (had to hard-code a lots of stuff, like 
`"calibrateName":"/opt/darc/lib/librtccalibrate.so"`

hubertz @ipag-9102 /opt/darc/bin > ./darcmagic  status
1+1 threads
Iteration: 4901/-1
Max time 0.0383480340242s at iter 2950
Frame time 0.0321819484234s (31.0733205723Hz)
Running...
FS: 0
Sending to mirror
Cam: 4900
No calibration:
No centroider:
No reconstructor:
No figure:
No buffer:
No mirror:
Clipped: 0
hubertz @ipag-9102 /opt/darc/bin >

How do I read an image now ?

**Comment by Zolko-123** [comment]
ha, I got it: darcplot. I have an image from my webcam

**Comment by Zolko-123** [comment]
at full 1Hz !!!

**Comment by agb32** [comment]
So, for the calibrateName, you need to put /opt/darc/lib in your LD_LIBRARY_PATH.  The make install script will suggest that you need to do this.
In darcplot, right click, select "Sub", and change the decimation - if you set it to 1, you should then get every frame, so 30Hz, or whatever your webcam is running at.

**Comment by Zolko-123** [comment]
`Frame time 0.0319560468197s (31.2929820651Hz)`

but in the GUI I have like 1Hz. I've set the rtcPxlBuf decimation to 1 in all columns, but still 1Hz.

**Comment by agb32** [comment]
What does ```darcmagic decimate``` give?
If you click on the button next to the decimation entries, I think that might force something.

**Comment by Zolko-123** [comment]
hubertz @ipag-9102 /opt/darc/bin > ./darcmagic decimate
Deprecation warning: GetDecimation called withPrefix==1.  At some point, the default will be changed to zero - please update your code.
rtcActuatorBuf: 0
rtcCalPxlBuf: 0
rtcCentBuf: 0
rtcErrorBuf: 1
rtcFluxBuf: 0
rtcMirrorBuf: 0
rtcPxlBuf: 1
rtcStatusBuf: 0
rtcSubLocBuf: 0
rtcTimeBuf: 0

******* Local values *******
rtcActuatorBuf: 0
rtcCalPxlBuf: 0
rtcCentBuf: 0
rtcErrorBuf: 1
rtcFluxBuf: 0
rtcMirrorBuf: 0
rtcPxlBuf: 1
rtcStatusBuf: 0
rtcSubLocBuf: 0
rtcTimeBuf: 0
hubertz @ipag-9102 /opt/darc/bin >

**Comment by agb32** [comment]
Seems ok...

**Comment by Zolko-123** [comment]
I've set the decimation rate to 1 in the config file plotRawPxls.xml. Yes, I know, very crude, but it did it, I have full Hz on the GUI

**Comment by agb32** [comment]
I think clicking the button or pressing return in the "Sub" window (decimation values) should do it...

**Comment by Zolko-123** [comment]
Yes, you're right, that works. Thanx

**Comment by Zolko-123** [comment]
> you need to put /opt/darc/lib in your LD_LIBRARY_PATH

yes, but that doesn't work with sudo.

**Comment by agb32** [comment]
Put in /etc/bash.bashrc
